language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

services:
  - mysql

addons:
  hosts:
    - api.boilerplate.local

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # Setup mysql database and password
  - mysql -e 'CREATE DATABASE boilerplate_test;'
  - mysqladmin -h127.0.0.1 -u root password 'root'

before_script:
  # Show some versions and env information
  - php --version
  - composer --version

install:
  # API - update composer
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.3.1"
  - cd api
  - travis_retry composer update --prefer-dist --no-interaction
  # Setup application, skip this as coookieValidationKey is already configured. In production environment, cookieValidationKey must be changed.
  #- sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" api/config/web.php
  # Make sure changing back to root directory
  - cd ..
script:
  - cd api
  # Run migration first
  - ./tests/bin/yii migrate --migrationPath=@yii/rbac/migrations/ --interactive=0
  - ./tests/bin/yii migrate up --interactive=0
  # Run api using built-in PHP server
  - php -S api.boilerplate.local:8080 -t web > /dev/null 2>&1 &
  # Run codeception
  - ./vendor/bin/codecept run -vvv